script.js doesn't contain: ["addEventListener", "DOMContentLoaded", "function"]
script.js doesn't contain: ["document.getElementById", "registration-form"] 
script.js doesn't contain: ["form-feedback"]
script.js doesn't contain: ["username", "email", "password", "trim"]
script.js doesn't contain: ["push"] 
script.js doesn't contain: ["isValid"]  
script.js doesn't contain: ["feedbackDiv.innerHTML", "messages.join"]
script.js doesn't contain: ["display"] / script.js doesn't contain: ["Registration successful"] / script.js doesn't contain: ["br", "feedbackDiv.style.color", "#dc3545"]
script.js doesn't contain: ["username.length"]
script.js doesn't contain: ["password.length", "8"]
script.js doesn't contain: ["password.length", "8"]
