script.js doesn't contain: ["addEventListener", "DOMContentLoaded", "function"]
script.js doesn't contain: ["document.getElementById", "registration-form"] 
script.js doesn't contain: ["form-feedback"]
script.js doesn't contain: ["username", "email", "password", "trim"]
script.js doesn't contain: ["push"] 
script.js doesn't contain: ["feedbackDiv.innerHTML", "messages.join"]
